# Generated by Django 4.0.2 on 2022-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(blank=True)),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'Medium'), ('L', 'large')], max_length=150)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Violet', 'Violet')], max_length=150)),
                ('description', models.TextField(max_length=150)),
                ('availabilty', models.BooleanField(default=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
