# Generated by Django 4.0.2 on 2022-02-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(blank=True, to='product.Material'),
        ),
    ]
