# Generated by Django 4.0.2 on 2022-02-15 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='Wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
